### ISSUE TITLE
Color helpers don't work when map keys are CSS colors

### ISSUE THREAD

**Issue by cmalven** [onedesign/one-sass-toolkit#16]
Just discovered something really dumb and frustrating:

If you use unquoted color names as keys in a SASS map, Sass will always automatically convert that name to a hexidecimal value any time it is output.

```scss
$colors: (
  black: #191919, // This one will cause issues
  dark-black: #0d0d0d, // This one won't, because there is no "dark-black" css color
);
```

Therefore, when we output the helper classes for the above, we will end up with the following:

```css
.h-color-text-#000{color:#191919}
.h-color-bg-#000{background-color:#191919}
.h-color-text-dark-black{color:#0d0d0d}
.h-color-bg-dark-black{background-color:#0d0d0d}
```

To make things even more confusing, Sass will _only_ do this when the output mode is `compressed`, otherwise it will work just fine.

This is stupid and maddening to me beyond belief, and I haven't been able to find a simple way to prevent sass from doing this. The "official" suggestion from the Sass team is to quote your map values like so:

```scss
$colors: (
  'black': #191919,
  'dark-black': #0d0d0d
);
```

But I'm not really willing to do that to solve such a dumb problem. @brianjhanson do you have any ideas about how to sidestep this?
